import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    host: true,
    port: 5173,
    allowedHosts: ['frontend', 'localhost'],
    watch: {
      usePolling: true,
      interval: 500,
    },
    proxy: {
      '/ValueSet': 'http://backend:8000',
      '/CodeSystem': 'http://backend:8000',
      '/ConceptMap': 'http://backend:8000',
      '/Patient': 'http://backend:8000',
      '/Observation': 'http://backend:8000',
      '/Condition': 'http://backend:8000',
      '/Encounter': 'http://backend:8000',
      '/AllergyIntolerance': 'http://backend:8000',
      '/Immunization': 'http://backend:8000',
      '/Organization': 'http://backend:8000',
      '/Practitioner': 'http://backend:8000',
      '/PractitionerRole': 'http://backend:8000',
      '/Location': 'http://backend:8000',
      '/MedicationRequest': 'http://backend:8000',
      '/Procedure': 'http://backend:8000',
      '/DiagnosticReport': 'http://backend:8000',
      '/_history': 'http://backend:8000',
      '/analytics': 'http://backend:8000',
      '/sdo': 'http://backend:8000',
      '/ai': 'http://backend:8000',
      '/health': 'http://backend:8000',
      '/ready': 'http://backend:8000',
      '/metadata': 'http://backend:8000',
      '/StructureDefinition': 'http://backend:8000',
      '/jobs': 'http://backend:8000',
      '/bulk': 'http://backend:8000',
      '/admin': 'http://backend:8000',
      '/mcp-chat': 'http://backend:8000',
      '/docs': 'http://backend:8000',
      '/redoc': 'http://backend:8000',
      '/openapi.json': 'http://backend:8000',
    },
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/tests/setup.ts'],
  },
})
